version: '{build}'

init:
- git config --global core.autocrlf input

# c++14 is available on Qt 5.4 and up
environment:
  #32-bit
  matrix:
  - QT5: C:\Qt\5.3\mingw482_32
    MINGW: C:\Qt\Tools\mingw482_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    use_cmake: "false"
  - QT5: C:\Qt\5.4\mingw491_32
    MINGW: C:\Qt\Tools\mingw491_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    use_cmake: "false"
  - QT5: C:\Qt\5.5\mingw492_32
    MINGW: C:\Qt\Tools\mingw492_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    use_cmake: "false"
  - QT5: C:\Qt\5.6.3\mingw49_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"
  - QT5: C:\Qt\5.7\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    use_cmake: "false"
  - QT5: C:\Qt\5.8\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2013
    use_cmake: "false"
  - QT5: C:\Qt\5.9\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"
  - QT5: C:\Qt\5.10\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"
  - QT5: C:\Qt\5.11\mingw53_32
    MINGW: C:\Qt\Tools\mingw530_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"
  - QT5: C:\Qt\5.12\mingw73_32
    MINGW: C:\Qt\Tools\mingw730_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"
  - QT5: C:\Qt\5.13\mingw73_32
    MINGW: C:\Qt\Tools\mingw730_32
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"
  #64-bit
  - QT5: C:\Qt\5.12\mingw73_64
    MINGW: C:\Qt\Tools\mingw730_64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    use_cmake: "false"
  - QT5: C:\Qt\5.13\mingw73_64
    MINGW: C:\Qt\Tools\mingw730_64
    APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    use_cmake: "false"

matrix:
  # If at least one job has failed the entire build is marked as failed
  fast_finish: true

before_build:
- set PATH=%MINGW%\bin;%QT5%\bin;%PATH%

build_script:
- mkdir build
- cd build

# build library and tests
- if [%use_cmake%]==[true] (
    cmake --version &&
    cmake -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release .. &&
    make
  )
  else (
    qmake -v &&
    qmake ..\Gilligan.pro CONFIG+=release CONFIG+=c++11 DESTDIR=%cd% &&
    mingw32-make &&
    mingw32-make
  )

  # email notifications set at https://ci.appveyor.com/notifications
  