language: cpp

matrix:
 include:
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=56 USE_CMAKE=true
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=57 USE_CMAKE=true
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=58 USE_CMAKE=true
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=59 USE_CMAKE=true
  - os: linux
    dist: xenial
    sudo: required
    compiler: gcc
    env:
     - QT_BASE=510 USE_CMAKE=true
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=511
  - os: linux
    dist: xenial
    compiler: gcc
    env:
     - QT_BASE=511 USE_CMAKE=true
  #- os: osx
  #  compiler: clang
  #  env:
  #   - QT_BASE=511
  #- os: osx
  #  compiler: clang
  #  env:
  #   - QT_BASE=511 USE_CMAKE=true
  - os: linux
    dist: xenial
    compiler: gcc
    env:
      - QT_BASE=512
  - os: linux
    dist: xenial
    compiler: gcc
    env:
    - QT_BASE=512 USE_CMAKE=true
  #- os: osx
  #  compiler: clang
  #  env:
  #   - QT_BASE=512
  #- os: osx
  #  compiler: clang
  #  env:
  #   - QT_BASE=512 USE_CMAKE=true
  - os: osx
    compiler: clang
    env:
     - QT_BASE=513
  - os: osx
    compiler: clang
    env:
    - QT_BASE=513 USE_CMAKE=true

before_install:
  - if [ "$QT_BASE" = "56" ]; then sudo add-apt-repository ppa:beineri/opt-qt563-xenial -y; fi
  - if [ "$QT_BASE" = "57" ]; then sudo add-apt-repository ppa:beineri/opt-qt571-xenial -y; fi
  - if [ "$QT_BASE" = "58" ]; then sudo add-apt-repository ppa:beineri/opt-qt58-xenial -y; fi
  - if [ "$QT_BASE" = "59" ]; then sudo add-apt-repository ppa:beineri/opt-qt595-xenial -y; fi
  - if [ "$QT_BASE" = "510" ]; then sudo add-apt-repository ppa:beineri/opt-qt-5.10.1-xenial -y; fi
  - if [[ "$QT_BASE" = "511" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.11.3-xenial -y; fi
  - if [[ "$QT_BASE" = "512" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo add-apt-repository ppa:beineri/opt-qt-5.12.6-xenial -y; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-get update -qq;
    else
      brew update;
    fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt install mesa-common-dev libglu1-mesa-dev;
    fi

install:
  - if [ "$QT_BASE" = "56" ]; then sudo apt-get install -qq qt56base; source /opt/qt56/bin/qt56-env.sh; fi
  - if [ "$QT_BASE" = "57" ]; then sudo apt-get install -qq qt57base; source /opt/qt57/bin/qt57-env.sh; fi
  - if [ "$QT_BASE" = "58" ]; then sudo apt-get install -qq qt58base; source /opt/qt58/bin/qt58-env.sh; fi
  - if [ "$QT_BASE" = "59" ]; then sudo apt-get install -qq qt59base; source /opt/qt59/bin/qt59-env.sh; fi
  - if [ "$QT_BASE" = "510" ]; then sudo apt-get install -qq qt510base; source /opt/qt510/bin/qt510-env.sh; fi
  - if [[ "$QT_BASE" = "511" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt511base; source /opt/qt511/bin/qt511-env.sh; fi
  - if [[ "$QT_BASE" = "512" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt512base; source /opt/qt512/bin/qt512-env.sh; fi
  - if [[ "$QT_BASE" = "513" && "$TRAVIS_OS_NAME" = "linux" ]]; then sudo apt-get install -qq qt513base; source /opt/qt513/bin/qt513-env.sh; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install qt;
      brew link --force qt;
      export HOMEBREW_QT5_VERSION=$(brew list --versions qt | rev | cut -d' ' -f1 | rev);
      sudo ln -s /usr/local/Cellar/qt/$HOMEBREW_QT5_VERSION/mkspecs /usr/local/mkspecs;
      sudo ln -s /usr/local/Cellar/qt/$HOMEBREW_QT5_VERSION/plugins /usr/local/plugins;
    fi

script:
  # build library and tests, install library
  - mkdir -v build 
  - cd build
  - echo $(pwd)
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      gcc -v;
    else
      clang -v;
    fi
  - if [ "$USE_CMAKE" = "true" ]; then
      cmake --version;
      cmake -DCMAKE_BUILD_TYPE=Release ..;
    else
      qmake -v;
      qmake ../Gilligan.pro CONFIG+=release;
    fi
  - make;
  - sudo make install;

notifications:
  email: true